modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"

[[mods]]
modId="diamantinocraft"
version="1.0.0"
displayName="DiamantinoCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="DiamantinoOp"

[[dependencies.diamantinocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




